name: Bump version
on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    uses: The-Poolz/.net-workflows/.github/workflows/bump-version.yml@v1.0.3
